const cards = [
  { word: "die Erfahrung", sentence: "Ich habe viel Erfahrung gesammelt, seit ich in Deutschland arbeite.", translationWord: "die Erfahrung = experience", translationSentence: "I have gained a lot of experience since I have been working in Germany." },
  { word: "die Gesellschaft", sentence: "In unserer Gesellschaft spielt Bildung eine wichtige Rolle.", translationWord: "die Gesellschaft = society", translationSentence: "In our society, education plays an important role." },
  { word: "das Ergebnis", sentence: "Das Ergebnis der Prüfung war besser, als ich erwartet hatte.", translationWord: "das Ergebnis = result", translationSentence: "The result of the exam was better than I had expected." },
  { word: "die Möglichkeit", sentence: "Wir haben die Möglichkeit, an einem Austauschprogramm teilzunehmen.", translationWord: "die Möglichkeit = opportunity", translationSentence: "We have the opportunity to take part in an exchange program." },
  { word: "die Verantwortung", sentence: "Eltern tragen die Verantwortung für ihre Kinder.", translationWord: "die Verantwortung = responsibility", translationSentence: "Parents bear responsibility for their children." },
  { word: "der Unterschied", sentence: "Es gibt einen großen Unterschied zwischen Stadt- und Landleben.", translationWord: "der Unterschied = difference", translationSentence: "There is a big difference between city and country life." },
  { word: "die Beziehung", sentence: "Sie pflegt eine gute Beziehung zu ihren Kollegen.", translationWord: "die Beziehung = relationship", translationSentence: "She maintains a good relationship with her colleagues." },
  { word: "die Umwelt", sentence: "Viele Menschen möchten die Umwelt besser schützen.", translationWord: "die Umwelt = environment", translationSentence: "Many people want to protect the environment better." },
  { word: "die Entwicklung", sentence: "Die technologische Entwicklung schreitet schnell voran.", translationWord: "die Entwicklung = development", translationSentence: "Technological development is progressing rapidly." },
  { word: "das Verhalten", sentence: "Sein Verhalten im Unterricht war heute sehr respektvoll.", translationWord: "das Verhalten = behavior", translationSentence: "His behavior in class was very respectful today." },

  { word: "der Vorteil", sentence: "Ein Vorteil des Fahrrads ist, dass es umweltfreundlich ist.", translationWord: "der Vorteil = advantage", translationSentence: "An advantage of the bicycle is that it is environmentally friendly." },
  { word: "der Nachteil", sentence: "Ein Nachteil der Großstadt ist der viele Lärm.", translationWord: "der Nachteil = disadvantage", translationSentence: "A disadvantage of the big city is the noise." },
  { word: "die Erfahrung", sentence: "Diese Reise war für mich eine wertvolle Erfahrung.", translationWord: "die Erfahrung = experience", translationSentence: "This trip was a valuable experience for me." },
  { word: "das Beispiel", sentence: "Dieses Beispiel zeigt, wie wichtig Teamarbeit ist.", translationWord: "das Beispiel = example", translationSentence: "This example shows how important teamwork is." },
  { word: "die Meinung", sentence: "Meiner Meinung nach sollte man mehr Sport treiben.", translationWord: "die Meinung = opinion", translationSentence: "In my opinion, people should do more sports." },
  { word: "der Eindruck", sentence: "Ich hatte den Eindruck, dass er die Wahrheit sagt.", translationWord: "der Eindruck = impression", translationSentence: "I had the impression that he was telling the truth." },
  { word: "die Entscheidung", sentence: "Die Entscheidung fiel nach langen Diskussionen.", translationWord: "die Entscheidung = decision", translationSentence: "The decision was made after long discussions." },
  { word: "die Möglichkeit", sentence: "Wir haben mehrere Möglichkeiten, dieses Problem zu lösen.", translationWord: "die Möglichkeit = possibility", translationSentence: "We have several possibilities to solve this problem." },
  { word: "das Ziel", sentence: "Mein Ziel ist es, nächstes Jahr das B2-Niveau zu erreichen.", translationWord: "das Ziel = goal", translationSentence: "My goal is to reach the B2 level next year." },
  { word: "die Zukunft", sentence: "Viele junge Menschen machen sich Sorgen um die Zukunft.", translationWord: "die Zukunft = future", translationSentence: "Many young people worry about the future." },

  { word: "die Vergangenheit", sentence: "Manchmal denkt er gern an die Vergangenheit zurück.", translationWord: "die Vergangenheit = past", translationSentence: "Sometimes he likes to think back to the past." },
  { word: "die Gegenwart", sentence: "Wir sollten in der Gegenwart leben und den Moment genießen.", translationWord: "die Gegenwart = present", translationSentence: "We should live in the present and enjoy the moment." },
  { word: "die Aufmerksamkeit", sentence: "Sie hörte dem Lehrer mit großer Aufmerksamkeit zu.", translationWord: "die Aufmerksamkeit = attention", translationSentence: "She listened to the teacher with great attention." },
  { word: "das Interesse", sentence: "Ich habe großes Interesse an moderner Kunst.", translationWord: "das Interesse = interest", translationSentence: "I have great interest in modern art." },
  { word: "der Einfluss", sentence: "Seine Eltern haben einen starken Einfluss auf ihn.", translationWord: "der Einfluss = influence", translationSentence: "His parents have a strong influence on him." },
  { word: "die Leistung", sentence: "Seine sportliche Leistung war beeindruckend.", translationWord: "die Leistung = performance", translationSentence: "His athletic performance was impressive." },
  { word: "die Hoffnung", sentence: "Wir haben die Hoffnung, dass alles gut wird.", translationWord: "die Hoffnung = hope", translationSentence: "We have the hope that everything will be fine." },
  { word: "die Möglichkeit", sentence: "Es besteht die Möglichkeit, dass es morgen regnet.", translationWord: "die Möglichkeit = possibility", translationSentence: "There is a possibility that it will rain tomorrow." },
  { word: "der Grund", sentence: "Der Grund für sein Fehlen war eine Krankheit.", translationWord: "der Grund = reason", translationSentence: "The reason for his absence was an illness." },
  { word: "die Ursache", sentence: "Die Ursache des Problems ist noch unklar.", translationWord: "die Ursache = cause", translationSentence: "The cause of the problem is still unclear." },

  { word: "die Lösung", sentence: "Wir müssen eine Lösung für dieses Problem finden.", translationWord: "die Lösung = solution", translationSentence: "We need to find a solution for this problem." },
  { word: "die Frage", sentence: "Die Frage war schwer zu beantworten.", translationWord: "die Frage = question", translationSentence: "The question was hard to answer." },
  { word: "die Antwort", sentence: "Seine Antwort war sehr überzeugend.", translationWord: "die Antwort = answer", translationSentence: "His answer was very convincing." },
  { word: "die Erklärung", sentence: "Die Lehrerin gab eine klare Erklärung des Textes.", translationWord: "die Erklärung = explanation", translationSentence: "The teacher gave a clear explanation of the text." },
  { word: "der Text", sentence: "Der Text enthält viele interessante Informationen.", translationWord: "der Text = text", translationSentence: "The text contains a lot of interesting information." },
  { word: "die Bedeutung", sentence: "Das Wort hat mehrere Bedeutungen.", translationWord: "die Bedeutung = meaning", translationSentence: "The word has several meanings." },
  { word: "die Sprache", sentence: "Er spricht drei Sprachen fließend.", translationWord: "die Sprache = language", translationSentence: "He speaks three languages fluently." },
  { word: "der Ausdruck", sentence: "Dieser Ausdruck ist typisch für die Jugendsprache.", translationWord: "der Ausdruck = expression", translationSentence: "This expression is typical for youth language." },
  { word: "das Wort", sentence: "Ich habe ein neues Wort gelernt.", translationWord: "das Wort = word", translationSentence: "I learned a new word." },
  { word: "der Satz", sentence: "Der Satz ist grammatisch korrekt.", translationWord: "der Satz = sentence", translationSentence: "The sentence is grammatically correct." },

  { word: "die Nachricht", sentence: "Ich habe gestern eine wichtige Nachricht erhalten.", translationWord: "die Nachricht = message/news", translationSentence: "I received an important message yesterday." },
  { word: "die Zeitung", sentence: "Ich lese jeden Morgen die Zeitung.", translationWord: "die Zeitung = newspaper", translationSentence: "I read the newspaper every morning." },
  { word: "die Werbung", sentence: "Die Werbung im Fernsehen ist oft sehr laut.", translationWord: "die Werbung = advertisement", translationSentence: "The advertising on TV is often very loud." },
  { word: "das Fernsehen", sentence: "Im Fernsehen läuft heute ein interessanter Film.", translationWord: "das Fernsehen = television", translationSentence: "A interesting movie is on television today." },
  { word: "das Radio", sentence: "Im Radio spielen sie gerade mein Lieblingslied.", translationWord: "das Radio = radio", translationSentence: "They are playing my favorite song on the radio right now." },
  { word: "das Internet", sentence: "Viele Jugendliche verbringen viel Zeit im Internet.", translationWord: "das Internet = internet", translationSentence: "Many young people spend a lot of time on the internet." },
  { word: "die Kommunikation", sentence: "Gute Kommunikation ist wichtig für eine erfolgreiche Zusammenarbeit.", translationWord: "die Kommunikation = communication", translationSentence: "Good communication is important for successful cooperation." },
  { word: "die Information", sentence: "Ich habe viele Informationen über das Thema gesammelt.", translationWord: "die Information = information", translationSentence: "I have gathered a lot of information about the topic." },
  { word: "der Brief", sentence: "Sie schrieb einen langen Brief an ihre Freundin.", translationWord: "der Brief = letter", translationSentence: "She wrote a long letter to her friend." },
  { word: "die E-Mail", sentence: "Ich habe dir gestern eine E-Mail geschickt.", translationWord: "die E-Mail = email", translationSentence: "I sent you an email yesterday." }
];
cards.push(
  { word: "die Geschichte", sentence: "Die Geschichte spielt im 19. Jahrhundert.", translationWord: "die Geschichte = story/history", translationSentence: "The story takes place in the 19th century." },
  { word: "die Kultur", sentence: "Die deutsche Kultur ist sehr vielfältig.", translationWord: "die Kultur = culture", translationSentence: "German culture is very diverse." },
  { word: "die Kunst", sentence: "Er interessiert sich sehr für moderne Kunst.", translationWord: "die Kunst = art", translationSentence: "He is very interested in modern art." },
  { word: "die Literatur", sentence: "Die deutsche Literatur hat viele berühmte Dichter hervorgebracht.", translationWord: "die Literatur = literature", translationSentence: "German literature has produced many famous poets." },
  { word: "die Musik", sentence: "Musik spielt in meinem Leben eine große Rolle.", translationWord: "die Musik = music", translationSentence: "Music plays a big role in my life." },
  { word: "das Theater", sentence: "Wir gehen morgen ins Theater.", translationWord: "das Theater = theater", translationSentence: "We are going to the theater tomorrow." },
  { word: "der Film", sentence: "Der Film war spannender als das Buch.", translationWord: "der Film = film/movie", translationSentence: "The film was more exciting than the book." },
  { word: "das Konzert", sentence: "Das Konzert war bereits nach einer Stunde ausverkauft.", translationWord: "das Konzert = concert", translationSentence: "The concert was sold out after just one hour." },
  { word: "das Museum", sentence: "Im Museum gibt es eine neue Ausstellung.", translationWord: "das Museum = museum", translationSentence: "There is a new exhibition in the museum." },
  { word: "die Ausstellung", sentence: "Die Ausstellung moderner Kunst war sehr interessant.", translationWord: "die Ausstellung = exhibition", translationSentence: "The exhibition of modern art was very interesting." },

  { word: "die Freizeit", sentence: "In meiner Freizeit gehe ich gern schwimmen.", translationWord: "die Freizeit = free time", translationSentence: "In my free time, I like to go swimming." },
  { word: "das Hobby", sentence: "Sein größtes Hobby ist das Fotografieren.", translationWord: "das Hobby = hobby", translationSentence: "His biggest hobby is photography." },
  { word: "der Sport", sentence: "Sport ist gut für die Gesundheit.", translationWord: "der Sport = sport", translationSentence: "Sport is good for your health." },
  { word: "das Spiel", sentence: "Das Spiel endete unentschieden.", translationWord: "das Spiel = game", translationSentence: "The game ended in a draw." },
  { word: "die Mannschaft", sentence: "Unsere Mannschaft hat das Turnier gewonnen.", translationWord: "die Mannschaft = team", translationSentence: "Our team won the tournament." },
  { word: "der Spieler", sentence: "Der Spieler hat drei Tore geschossen.", translationWord: "der Spieler = player", translationSentence: "The player scored three goals." },
  { word: "der Gewinner", sentence: "Der Gewinner des Wettbewerbs bekommt einen Preis.", translationWord: "der Gewinner = winner", translationSentence: "The winner of the competition gets a prize." },
  { word: "der Verlierer", sentence: "Auch der Verlierer hat sein Bestes gegeben.", translationWord: "der Verlierer = loser", translationSentence: "Even the loser gave his best." },
  { word: "der Erfolg", sentence: "Der Erfolg kam nach vielen Jahren harter Arbeit.", translationWord: "der Erfolg = success", translationSentence: "Success came after many years of hard work." },
  { word: "das Ziel", sentence: "Um ein Ziel zu erreichen, braucht man Disziplin.", translationWord: "das Ziel = goal/aim", translationSentence: "To achieve a goal, you need discipline." },

  { word: "der Körper", sentence: "Der menschliche Körper ist sehr komplex.", translationWord: "der Körper = body", translationSentence: "The human body is very complex." },
  { word: "der Kopf", sentence: "Sie hat starke Kopfschmerzen.", translationWord: "der Kopf = head", translationSentence: "She has a strong headache." },
  { word: "das Herz", sentence: "Mein Herz schlägt schneller, wenn ich nervös bin.", translationWord: "das Herz = heart", translationSentence: "My heart beats faster when I am nervous." },
  { word: "die Hand", sentence: "Er gab mir die Hand zur Begrüßung.", translationWord: "die Hand = hand", translationSentence: "He shook my hand in greeting." },
  { word: "der Fuß", sentence: "Nach dem langen Spaziergang tun mir die Füße weh.", translationWord: "der Fuß = foot", translationSentence: "My feet hurt after the long walk." },
  { word: "das Auge", sentence: "Sie hat blaue Augen.", translationWord: "das Auge = eye", translationSentence: "She has blue eyes." },
  { word: "das Ohr", sentence: "Ich habe Musik mit meinen neuen Kopfhörern im Ohr.", translationWord: "das Ohr = ear", translationSentence: "I have music in my ear with my new headphones." },
  { word: "der Mund", sentence: "Sie öffnete den Mund, um etwas zu sagen.", translationWord: "der Mund = mouth", translationSentence: "She opened her mouth to say something." },
  { word: "die Nase", sentence: "Im Winter bekomme ich oft eine laufende Nase.", translationWord: "die Nase = nose", translationSentence: "In winter, I often get a runny nose." },
  { word: "das Gesicht", sentence: "Sein Gesicht war vor Freude strahlend.", translationWord: "das Gesicht = face", translationSentence: "His face was beaming with joy." },

  { word: "die Gesundheit", sentence: "Gesundheit ist wichtiger als Reichtum.", translationWord: "die Gesundheit = health", translationSentence: "Health is more important than wealth." },
  { word: "die Krankheit", sentence: "Die Krankheit dauerte mehrere Wochen.", translationWord: "die Krankheit = illness", translationSentence: "The illness lasted several weeks." },
  { word: "der Arzt", sentence: "Der Arzt hat mir ein Medikament verschrieben.", translationWord: "der Arzt = doctor", translationSentence: "The doctor prescribed me a medicine." },
  { word: "die Ärztin", sentence: "Die Ärztin untersucht den Patienten gründlich.", translationWord: "die Ärztin = doctor (female)", translationSentence: "The doctor examines the patient thoroughly." },
  { word: "das Krankenhaus", sentence: "Er musste wegen einer Operation ins Krankenhaus.", translationWord: "das Krankenhaus = hospital", translationSentence: "He had to go to the hospital for an operation." },
  { word: "die Apotheke", sentence: "In der Apotheke bekommt man Medikamente.", translationWord: "die Apotheke = pharmacy", translationSentence: "You can get medicine at the pharmacy." },
  { word: "die Medizin", sentence: "Die Medizin hat mir schnell geholfen.", translationWord: "die Medizin = medicine", translationSentence: "The medicine helped me quickly." },
  { word: "das Medikament", sentence: "Dieses Medikament sollte man dreimal täglich nehmen.", translationWord: "das Medikament = medicine/drug", translationSentence: "You should take this medicine three times a day." },
  { word: "die Verletzung", sentence: "Er hatte nach dem Unfall eine schwere Verletzung.", translationWord: "die Verletzung = injury", translationSentence: "He had a serious injury after the accident." },
  { word: "die Untersuchung", sentence: "Die Untersuchung beim Arzt dauerte eine halbe Stunde.", translationWord: "die Untersuchung = examination", translationSentence: "The examination at the doctor’s took half an hour." },

  { word: "der Unterricht", sentence: "Der Unterricht beginnt morgen um acht Uhr.", translationWord: "der Unterricht = lesson/class", translationSentence: "The class starts tomorrow at eight o'clock." },
  { word: "die Schule", sentence: "Die Schule liegt in der Nähe meines Hauses.", translationWord: "die Schule = school", translationSentence: "The school is near my house." },
  { word: "der Schüler", sentence: "Die Schüler machen eine Klassenarbeit.", translationWord: "der Schüler = student/pupil (male)", translationSentence: "The students are doing a test." },
  { word: "die Schülerin", sentence: "Die Schülerin hat sehr gute Noten.", translationWord: "die Schülerin = student/pupil (female)", translationSentence: "The female student has very good grades." },
  { word: "der Lehrer", sentence: "Der Lehrer erklärt die Grammatik.", translationWord: "der Lehrer = teacher (male)", translationSentence: "The teacher explains the grammar." },
  { word: "die Lehrerin", sentence: "Die Lehrerin gibt viele Hausaufgaben.", translationWord: "die Lehrerin = teacher (female)", translationSentence: "The female teacher gives a lot of homework." },
  { word: "die Universität", sentence: "Er studiert seit zwei Jahren an der Universität.", translationWord: "die Universität = university", translationSentence: "He has been studying at the university for two years." },
  { word: "das Studium", sentence: "Das Studium der Medizin dauert lange.", translationWord: "das Studium = studies", translationSentence: "Medical studies take a long time." },
  { word: "die Prüfung", sentence: "Die Prüfung war schwieriger als erwartet.", translationWord: "die Prüfung = exam", translationSentence: "The exam was more difficult than expected." },
  { word: "die Note", sentence: "Sie hat in Mathe eine gute Note bekommen.", translationWord: "die Note = grade", translationSentence: "She got a good grade in math." }
);
cards.push(
  { word: "die Sprache", sentence: "Er lernt seit einem Jahr die spanische Sprache.", translationWord: "die Sprache = language", translationSentence: "He has been learning the Spanish language for a year." },
  { word: "der Satz", sentence: "Dieser Satz ist grammatisch korrekt.", translationWord: "der Satz = sentence", translationSentence: "This sentence is grammatically correct." },
  { word: "das Wort", sentence: "Ich kenne dieses Wort nicht.", translationWord: "das Wort = word", translationSentence: "I don’t know this word." },
  { word: "die Bedeutung", sentence: "Das Wort hat mehrere Bedeutungen.", translationWord: "die Bedeutung = meaning", translationSentence: "The word has several meanings." },
  { word: "die Aussprache", sentence: "Die Aussprache dieses Wortes ist schwierig.", translationWord: "die Aussprache = pronunciation", translationSentence: "The pronunciation of this word is difficult." },
  { word: "der Ausdruck", sentence: "Dieser Ausdruck wird oft im Alltag benutzt.", translationWord: "der Ausdruck = expression", translationSentence: "This expression is often used in everyday life." },
  { word: "die Kommunikation", sentence: "Gute Kommunikation ist wichtig in einer Beziehung.", translationWord: "die Kommunikation = communication", translationSentence: "Good communication is important in a relationship." },
  { word: "das Gespräch", sentence: "Das Gespräch dauerte fast zwei Stunden.", translationWord: "das Gespräch = conversation", translationSentence: "The conversation lasted almost two hours." },
  { word: "die Diskussion", sentence: "Die Diskussion zwischen den Politikern war heftig.", translationWord: "die Diskussion = discussion", translationSentence: "The discussion between the politicians was intense." },
  { word: "die Information", sentence: "Ich habe alle wichtigen Informationen erhalten.", translationWord: "die Information = information", translationSentence: "I received all the important information." },

  { word: "die Zeitung", sentence: "Er liest jeden Morgen die Zeitung.", translationWord: "die Zeitung = newspaper", translationSentence: "He reads the newspaper every morning." },
  { word: "das Magazin", sentence: "Das Magazin erscheint einmal im Monat.", translationWord: "das Magazin = magazine", translationSentence: "The magazine is published once a month." },
  { word: "die Nachricht", sentence: "Ich habe eine Nachricht von meiner Freundin bekommen.", translationWord: "die Nachricht = message/news", translationSentence: "I got a message from my friend." },
  { word: "die Werbung", sentence: "Im Fernsehen läuft zu viel Werbung.", translationWord: "die Werbung = advertisement", translationSentence: "There are too many ads on TV." },
  { word: "das Fernsehen", sentence: "Fernsehen ist für Kinder nicht immer geeignet.", translationWord: "das Fernsehen = television", translationSentence: "Television is not always suitable for children." },
  { word: "das Radio", sentence: "Im Radio läuft gerade mein Lieblingslied.", translationWord: "das Radio = radio", translationSentence: "My favorite song is playing on the radio right now." },
  { word: "der Sender", sentence: "Dieser Sender bringt gute Dokumentationen.", translationWord: "der Sender = channel/station", translationSentence: "This channel broadcasts good documentaries." },
  { word: "die Serie", sentence: "Ich schaue abends gern meine Lieblingsserie.", translationWord: "die Serie = series", translationSentence: "I like watching my favorite series in the evening." },
  { word: "der Schauspieler", sentence: "Der Schauspieler spielte seine Rolle hervorragend.", translationWord: "der Schauspieler = actor", translationSentence: "The actor played his role excellently." },
  { word: "die Schauspielerin", sentence: "Die Schauspielerin gewann einen wichtigen Preis.", translationWord: "die Schauspielerin = actress", translationSentence: "The actress won an important award." },

  { word: "die Politik", sentence: "Die Politik des Landes hat sich stark verändert.", translationWord: "die Politik = politics", translationSentence: "The politics of the country have changed a lot." },
  { word: "der Politiker", sentence: "Der Politiker hielt eine lange Rede.", translationWord: "der Politiker = politician", translationSentence: "The politician gave a long speech." },
  { word: "die Regierung", sentence: "Die Regierung plant neue Reformen.", translationWord: "die Regierung = government", translationSentence: "The government is planning new reforms." },
  { word: "das Gesetz", sentence: "Ein neues Gesetz wurde verabschiedet.", translationWord: "das Gesetz = law", translationSentence: "A new law was passed." },
  { word: "die Wahl", sentence: "Die Wahl findet im nächsten Jahr statt.", translationWord: "die Wahl = election", translationSentence: "The election will take place next year." },
  { word: "die Demokratie", sentence: "Demokratie bedeutet Freiheit für alle Bürger.", translationWord: "die Demokratie = democracy", translationSentence: "Democracy means freedom for all citizens." },
  { word: "die Freiheit", sentence: "Freiheit ist ein grundlegendes Menschenrecht.", translationWord: "die Freiheit = freedom", translationSentence: "Freedom is a fundamental human right." },
  { word: "das Recht", sentence: "Jeder Mensch hat das Recht auf Bildung.", translationWord: "das Recht = right/law", translationSentence: "Every person has the right to education." },
  { word: "die Ordnung", sentence: "In der Bibliothek herrscht strenge Ordnung.", translationWord: "die Ordnung = order", translationSentence: "There is strict order in the library." },
  { word: "die Sicherheit", sentence: "Sicherheit am Arbeitsplatz ist sehr wichtig.", translationWord: "die Sicherheit = safety/security", translationSentence: "Safety at work is very important." },

  { word: "das Wetter", sentence: "Das Wetter wird morgen sonnig.", translationWord: "das Wetter = weather", translationSentence: "The weather will be sunny tomorrow." },
  { word: "der Regen", sentence: "Der Regen hat den ganzen Tag gedauert.", translationWord: "der Regen = rain", translationSentence: "The rain lasted all day." },
  { word: "der Schnee", sentence: "Die Kinder spielen draußen im Schnee.", translationWord: "der Schnee = snow", translationSentence: "The children are playing outside in the snow." },
  { word: "der Wind", sentence: "Der Wind weht heute sehr stark.", translationWord: "der Wind = wind", translationSentence: "The wind is blowing very strongly today." },
  { word: "die Sonne", sentence: "Die Sonne scheint hell am Himmel.", translationWord: "die Sonne = sun", translationSentence: "The sun is shining brightly in the sky." },
  { word: "der Himmel", sentence: "Der Himmel ist heute ganz blau.", translationWord: "der Himmel = sky", translationSentence: "The sky is completely blue today." },
  { word: "der Mond", sentence: "Der Mond scheint in der Nacht.", translationWord: "der Mond = moon", translationSentence: "The moon shines at night." },
  { word: "der Stern", sentence: "Am Himmel sind viele Sterne zu sehen.", translationWord: "der Stern = star", translationSentence: "Many stars can be seen in the sky." },
  { word: "die Natur", sentence: "Die Natur ist im Frühling besonders schön.", translationWord: "die Natur = nature", translationSentence: "Nature is especially beautiful in spring." },
  { word: "die Landschaft", sentence: "Die Landschaft in den Alpen ist beeindruckend.", translationWord: "die Landschaft = landscape", translationSentence: "The landscape in the Alps is impressive." },

  { word: "der Berg", sentence: "Wir wandern am Wochenende auf einen hohen Berg.", translationWord: "der Berg = mountain", translationSentence: "We are hiking up a high mountain on the weekend." },
  { word: "das Tal", sentence: "Im Tal liegt ein kleines Dorf.", translationWord: "das Tal = valley", translationSentence: "There is a small village in the valley." },
  { word: "der Fluss", sentence: "Der Fluss fließt durch die Stadt.", translationWord: "der Fluss = river", translationSentence: "The river flows through the city." },
  { word: "der See", sentence: "Wir fahren im Sommer oft an den See.", translationWord: "der See = lake", translationSentence: "We often go to the lake in summer." },
  { word: "das Meer", sentence: "Im Sommer verbringen viele Menschen ihren Urlaub am Meer.", translationWord: "das Meer = sea", translationSentence: "Many people spend their vacation at the sea in summer." },
  { word: "der Wald", sentence: "Im Wald gibt es viele verschiedene Tiere.", translationWord: "der Wald = forest", translationSentence: "There are many different animals in the forest." },
  { word: "der Baum", sentence: "Der alte Baum steht noch im Garten.", translationWord: "der Baum = tree", translationSentence: "The old tree is still standing in the garden." },
  { word: "die Blume", sentence: "Die Blumen blühen im Frühling.", translationWord: "die Blume = flower", translationSentence: "The flowers bloom in spring." },
  { word: "das Tier", sentence: "Das Tier lebt im Zoo.", translationWord: "das Tier = animal", translationSentence: "The animal lives in the zoo." },
  { word: "der Vogel", sentence: "Ein Vogel sitzt auf dem Dach.", translationWord: "der Vogel = bird", translationSentence: "A bird is sitting on the roof." }
);
cards.push(
  { word: "der Hund", sentence: "Der Hund läuft jeden Morgen mit seinem Besitzer im Park.", translationWord: "der Hund = dog", translationSentence: "The dog runs with its owner in the park every morning." },
  { word: "die Katze", sentence: "Die Katze schläft gern auf dem Sofa.", translationWord: "die Katze = cat", translationSentence: "The cat likes to sleep on the sofa." },
  { word: "das Pferd", sentence: "Das Pferd galoppiert über die Wiese.", translationWord: "das Pferd = horse", translationSentence: "The horse is galloping across the meadow." },
  { word: "die Kuh", sentence: "Die Kühe stehen auf der Weide.", translationWord: "die Kuh = cow", translationSentence: "The cows are standing in the pasture." },
  { word: "das Schwein", sentence: "Das Schwein liegt im Stall.", translationWord: "das Schwein = pig", translationSentence: "The pig is lying in the stable." },
  { word: "das Schaf", sentence: "Die Schafe werden im Sommer geschoren.", translationWord: "das Schaf = sheep", translationSentence: "The sheep are sheared in summer." },
  { word: "die Ziege", sentence: "Die Ziege klettert auf den Felsen.", translationWord: "die Ziege = goat", translationSentence: "The goat climbs on the rocks." },
  { word: "der Fisch", sentence: "Der Fisch schwimmt im Teich.", translationWord: "der Fisch = fish", translationSentence: "The fish swims in the pond." },
  { word: "das Insekt", sentence: "Ein Insekt flog durchs offene Fenster.", translationWord: "das Insekt = insect", translationSentence: "An insect flew through the open window." },
  { word: "die Biene", sentence: "Die Bienen sammeln Nektar von den Blumen.", translationWord: "die Biene = bee", translationSentence: "The bees collect nectar from the flowers." },

  { word: "das Haus", sentence: "Das Haus hat einen großen Garten.", translationWord: "das Haus = house", translationSentence: "The house has a big garden." },
  { word: "die Wohnung", sentence: "Die Wohnung liegt im dritten Stock.", translationWord: "die Wohnung = apartment", translationSentence: "The apartment is on the third floor." },
  { word: "das Zimmer", sentence: "Mein Zimmer ist hell und freundlich eingerichtet.", translationWord: "das Zimmer = room", translationSentence: "My room is bright and nicely furnished." },
  { word: "das Wohnzimmer", sentence: "Im Wohnzimmer steht ein großes Sofa.", translationWord: "das Wohnzimmer = living room", translationSentence: "There is a big sofa in the living room." },
  { word: "das Schlafzimmer", sentence: "Im Schlafzimmer steht ein großes Bett.", translationWord: "das Schlafzimmer = bedroom", translationSentence: "There is a big bed in the bedroom." },
  { word: "die Küche", sentence: "Die Küche ist modern ausgestattet.", translationWord: "die Küche = kitchen", translationSentence: "The kitchen is modernly equipped." },
  { word: "das Badezimmer", sentence: "Das Badezimmer ist neben dem Schlafzimmer.", translationWord: "das Badezimmer = bathroom", translationSentence: "The bathroom is next to the bedroom." },
  { word: "der Balkon", sentence: "Auf dem Balkon stehen viele Pflanzen.", translationWord: "der Balkon = balcony", translationSentence: "There are many plants on the balcony." },
  { word: "der Garten", sentence: "Im Garten wachsen Tomaten und Gurken.", translationWord: "der Garten = garden", translationSentence: "Tomatoes and cucumbers are growing in the garden." },
  { word: "die Tür", sentence: "Die Tür zum Keller ist abgeschlossen.", translationWord: "die Tür = door", translationSentence: "The door to the basement is locked." },

  { word: "das Fenster", sentence: "Durch das Fenster sieht man die Berge.", translationWord: "das Fenster = window", translationSentence: "You can see the mountains through the window." },
  { word: "die Wand", sentence: "An der Wand hängt ein großes Bild.", translationWord: "die Wand = wall", translationSentence: "A big picture hangs on the wall." },
  { word: "die Decke", sentence: "Die Decke im Wohnzimmer ist sehr hoch.", translationWord: "die Decke = ceiling/blanket", translationSentence: "The ceiling in the living room is very high." },
  { word: "der Boden", sentence: "Der Boden ist frisch geputzt.", translationWord: "der Boden = floor/ground", translationSentence: "The floor has been freshly cleaned." },
  { word: "das Möbel", sentence: "Die Möbel im Esszimmer sind neu.", translationWord: "das Möbel = piece of furniture", translationSentence: "The furniture in the dining room is new." },
  { word: "der Tisch", sentence: "Auf dem Tisch stehen Teller und Gläser.", translationWord: "der Tisch = table", translationSentence: "Plates and glasses are on the table." },
  { word: "der Stuhl", sentence: "Neben dem Tisch steht ein Stuhl.", translationWord: "der Stuhl = chair", translationSentence: "There is a chair next to the table." },
  { word: "das Bett", sentence: "Das Bett ist sehr bequem.", translationWord: "das Bett = bed", translationSentence: "The bed is very comfortable." },
  { word: "der Schrank", sentence: "Im Schrank hängen viele Hemden.", translationWord: "der Schrank = cupboard/wardrobe", translationSentence: "Many shirts are hanging in the cupboard." },
  { word: "das Regal", sentence: "Im Regal stehen viele Bücher.", translationWord: "das Regal = shelf", translationSentence: "There are many books on the shelf." },

  { word: "die Lampe", sentence: "Die Lampe im Wohnzimmer ist sehr hell.", translationWord: "die Lampe = lamp", translationSentence: "The lamp in the living room is very bright." },
  { word: "der Fernseher", sentence: "Der Fernseher steht im Wohnzimmer.", translationWord: "der Fernseher = television set", translationSentence: "The TV is in the living room." },
  { word: "der Computer", sentence: "Der Computer ist schon zehn Jahre alt.", translationWord: "der Computer = computer", translationSentence: "The computer is already ten years old." },
  { word: "das Handy", sentence: "Mein Handy ist leider kaputt.", translationWord: "das Handy = mobile phone", translationSentence: "Unfortunately, my mobile phone is broken." },
  { word: "der Kühlschrank", sentence: "Im Kühlschrank stehen viele Getränke.", translationWord: "der Kühlschrank = refrigerator", translationSentence: "There are many drinks in the refrigerator." },
  { word: "der Herd", sentence: "Der Herd ist elektrisch.", translationWord: "der Herd = stove", translationSentence: "The stove is electric." },
  { word: "die Waschmaschine", sentence: "Die Waschmaschine steht im Keller.", translationWord: "die Waschmaschine = washing machine", translationSentence: "The washing machine is in the basement." },
  { word: "der Spiegel", sentence: "Im Flur hängt ein großer Spiegel.", translationWord: "der Spiegel = mirror", translationSentence: "There is a big mirror hanging in the hallway." },
  { word: "die Treppe", sentence: "Die Treppe führt in den ersten Stock.", translationWord: "die Treppe = stairs", translationSentence: "The stairs lead to the first floor." },
  { word: "der Aufzug", sentence: "Der Aufzug ist gerade kaputt.", translationWord: "der Aufzug = elevator", translationSentence: "The elevator is currently broken." },

  { word: "die Stadt", sentence: "Die Stadt hat mehr als eine Million Einwohner.", translationWord: "die Stadt = city", translationSentence: "The city has more than one million inhabitants." },
  { word: "das Dorf", sentence: "Das Dorf liegt am Rand des Waldes.", translationWord: "das Dorf = village", translationSentence: "The village is located at the edge of the forest." },
  { word: "die Straße", sentence: "Die Straße ist sehr breit und voll mit Autos.", translationWord: "die Straße = street", translationSentence: "The street is very wide and full of cars." },
  { word: "der Platz", sentence: "Auf dem Platz findet ein Markt statt.", translationWord: "der Platz = square/place", translationSentence: "A market takes place in the square." },
  { word: "die Brücke", sentence: "Die Brücke verbindet zwei Stadtteile.", translationWord: "die Brücke = bridge", translationSentence: "The bridge connects two parts of the city." },
  { word: "der Park", sentence: "Viele Leute gehen am Wochenende in den Park.", translationWord: "der Park = park", translationSentence: "Many people go to the park on the weekend." },
  { word: "die Kirche", sentence: "Die Kirche steht im Zentrum der Stadt.", translationWord: "die Kirche = church", translationSentence: "The church is in the center of the city." },
  { word: "das Geschäft", sentence: "Das Geschäft verkauft Kleidung und Schuhe.", translationWord: "das Geschäft = shop/business", translationSentence: "The store sells clothes and shoes." },
  { word: "das Kaufhaus", sentence: "Im Kaufhaus gibt es viele Abteilungen.", translationWord: "das Kaufhaus = department store", translationSentence: "There are many departments in the department store." },
  { word: "der Supermarkt", sentence: "Der Supermarkt hat bis 22 Uhr geöffnet.", translationWord: "der Supermarkt = supermarket", translationSentence: "The supermarket is open until 10 p.m." }
);
cards.push(
  { word: "der Markt", sentence: "Auf dem Markt kaufe ich frisches Obst und Gemüse.", translationWord: "der Markt = market", translationSentence: "I buy fresh fruit and vegetables at the market." },
  { word: "die Bäckerei", sentence: "Die Bäckerei verkauft sehr leckeres Brot.", translationWord: "die Bäckerei = bakery", translationSentence: "The bakery sells very tasty bread." },
  { word: "die Metzgerei", sentence: "In der Metzgerei gibt es frisches Fleisch.", translationWord: "die Metzgerei = butcher’s shop", translationSentence: "There is fresh meat at the butcher’s shop." },
  { word: "die Apotheke", sentence: "Die Apotheke befindet sich gleich neben der Post.", translationWord: "die Apotheke = pharmacy", translationSentence: "The pharmacy is right next to the post office." },
  { word: "die Bank", sentence: "Ich muss morgen zur Bank gehen.", translationWord: "die Bank = bank", translationSentence: "I have to go to the bank tomorrow." },
  { word: "die Post", sentence: "Die Post hat nur bis 18 Uhr geöffnet.", translationWord: "die Post = post office", translationSentence: "The post office is only open until 6 p.m." },
  { word: "das Hotel", sentence: "Wir übernachten in einem kleinen Hotel.", translationWord: "das Hotel = hotel", translationSentence: "We are staying overnight in a small hotel." },
  { word: "das Restaurant", sentence: "Das Restaurant ist für seine italienische Küche bekannt.", translationWord: "das Restaurant = restaurant", translationSentence: "The restaurant is known for its Italian cuisine." },
  { word: "das Café", sentence: "Im Café trinke ich gern einen Cappuccino.", translationWord: "das Café = café", translationSentence: "I like to drink a cappuccino at the café." },
  { word: "die Kneipe", sentence: "Wir treffen uns abends in der Kneipe.", translationWord: "die Kneipe = pub/bar", translationSentence: "We meet in the pub in the evening." },

  { word: "die Polizei", sentence: "Die Polizei untersucht den Unfall.", translationWord: "die Polizei = police", translationSentence: "The police are investigating the accident." },
  { word: "die Feuerwehr", sentence: "Die Feuerwehr löschte den Brand schnell.", translationWord: "die Feuerwehr = fire department", translationSentence: "The fire department quickly extinguished the fire." },
  { word: "der Bahnhof", sentence: "Der Zug fährt pünktlich vom Bahnhof ab.", translationWord: "der Bahnhof = train station", translationSentence: "The train departs on time from the station." },
  { word: "der Flughafen", sentence: "Der Flughafen ist 30 Kilometer von der Stadt entfernt.", translationWord: "der Flughafen = airport", translationSentence: "The airport is 30 kilometers away from the city." },
  { word: "die Haltestelle", sentence: "Die Bushaltestelle ist direkt vor der Schule.", translationWord: "die Haltestelle = stop/station", translationSentence: "The bus stop is right in front of the school." },
  { word: "die Fahrkarte", sentence: "Die Fahrkarte kostet drei Euro.", translationWord: "die Fahrkarte = ticket", translationSentence: "The ticket costs three euros." },
  { word: "der Fahrplan", sentence: "Der Fahrplan hängt an der Wand.", translationWord: "der Fahrplan = timetable", translationSentence: "The timetable is hanging on the wall." },
  { word: "das Verkehrsmittel", sentence: "Busse und Bahnen sind wichtige Verkehrsmittel.", translationWord: "das Verkehrsmittel = means of transport", translationSentence: "Buses and trains are important means of transport." },
  { word: "der Bus", sentence: "Der Bus kommt alle zehn Minuten.", translationWord: "der Bus = bus", translationSentence: "The bus comes every ten minutes." },
  { word: "die Straßenbahn", sentence: "Die Straßenbahn hält direkt am Marktplatz.", translationWord: "die Straßenbahn = tram", translationSentence: "The tram stops directly at the marketplace." },

  { word: "die U-Bahn", sentence: "Die U-Bahn fährt bis Mitternacht.", translationWord: "die U-Bahn = subway", translationSentence: "The subway runs until midnight." },
  { word: "der Zug", sentence: "Der Zug nach Berlin fährt um 9 Uhr ab.", translationWord: "der Zug = train", translationSentence: "The train to Berlin departs at 9 o’clock." },
  { word: "das Auto", sentence: "Das Auto steht in der Garage.", translationWord: "das Auto = car", translationSentence: "The car is in the garage." },
  { word: "das Fahrrad", sentence: "Er fährt jeden Tag mit dem Fahrrad zur Arbeit.", translationWord: "das Fahrrad = bicycle", translationSentence: "He rides his bike to work every day." },
  { word: "das Motorrad", sentence: "Das Motorrad ist sehr schnell.", translationWord: "das Motorrad = motorcycle", translationSentence: "The motorcycle is very fast." },
  { word: "das Schiff", sentence: "Das Schiff fährt über den Fluss.", translationWord: "das Schiff = ship", translationSentence: "The ship sails across the river." },
  { word: "das Flugzeug", sentence: "Das Flugzeug startet in wenigen Minuten.", translationWord: "das Flugzeug = airplane", translationSentence: "The airplane takes off in a few minutes." },
  { word: "der Fahrer", sentence: "Der Fahrer musste plötzlich bremsen.", translationWord: "der Fahrer = driver", translationSentence: "The driver had to brake suddenly." },
  { word: "der Passagier", sentence: "Die Passagiere steigen ins Flugzeug ein.", translationWord: "der Passagier = passenger", translationSentence: "The passengers are boarding the plane." },
  { word: "der Verkehr", sentence: "Der Verkehr in der Innenstadt ist sehr stark.", translationWord: "der Verkehr = traffic", translationSentence: "The traffic in the city center is very heavy." },

  { word: "die Ampel", sentence: "Die Ampel ist rot, also müssen wir warten.", translationWord: "die Ampel = traffic light", translationSentence: "The traffic light is red, so we have to wait." },
  { word: "die Kreuzung", sentence: "An der Kreuzung gibt es oft Staus.", translationWord: "die Kreuzung = intersection", translationSentence: "There are often traffic jams at the intersection." },
  { word: "die Straße", sentence: "Die Straße führt direkt zum Bahnhof.", translationWord: "die Straße = street", translationSentence: "The street leads directly to the station." },
  { word: "die Brücke", sentence: "Die Brücke ist über hundert Jahre alt.", translationWord: "die Brücke = bridge", translationSentence: "The bridge is over a hundred years old." },
  { word: "der Tunnel", sentence: "Der Tunnel ist fast zwei Kilometer lang.", translationWord: "der Tunnel = tunnel", translationSentence: "The tunnel is almost two kilometers long." },
  { word: "der Stau", sentence: "Wir stehen seit einer Stunde im Stau.", translationWord: "der Stau = traffic jam", translationSentence: "We have been stuck in a traffic jam for an hour." },
  { word: "der Unfall", sentence: "Bei dem Unfall wurde niemand verletzt.", translationWord: "der Unfall = accident", translationSentence: "Nobody was injured in the accident." },
  { word: "der Führerschein", sentence: "Er hat seit drei Jahren einen Führerschein.", translationWord: "der Führerschein = driver’s license", translationSentence: "He has had a driver’s license for three years." },
  { word: "die Tankstelle", sentence: "Wir müssen an der Tankstelle Benzin kaufen.", translationWord: "die Tankstelle = gas station", translationSentence: "We need to buy gas at the gas station." },
  { word: "das Benzin", sentence: "Das Benzin ist schon wieder teurer geworden.", translationWord: "das Benzin = gasoline", translationSentence: "The gasoline has become more expensive again." },

  { word: "die Reise", sentence: "Die Reise nach Spanien war sehr schön.", translationWord: "die Reise = trip/journey", translationSentence: "The trip to Spain was very nice." },
  { word: "der Urlaub", sentence: "Im Sommer machen wir drei Wochen Urlaub.", translationWord: "der Urlaub = vacation", translationSentence: "We go on vacation for three weeks in summer." },
  { word: "das Ziel", sentence: "Unser Ziel ist es, pünktlich anzukommen.", translationWord: "das Ziel = destination/goal", translationSentence: "Our destination is to arrive on time." },
  { word: "der Ausflug", sentence: "Am Wochenende machen wir einen Ausflug ins Gebirge.", translationWord: "der Ausflug = excursion", translationSentence: "At the weekend we are going on a trip to the mountains." },
  { word: "die Sehenswürdigkeit", sentence: "Paris hat viele berühmte Sehenswürdigkeiten.", translationWord: "die Sehenswürdigkeit = sight/attraction", translationSentence: "Paris has many famous sights." },
  { word: "der Tourist", sentence: "Die Touristen fotografieren den Dom.", translationWord: "der Tourist = tourist (male)", translationSentence: "The tourists are photographing the cathedral." },
  { word: "die Touristin", sentence: "Die Touristinnen kaufen Souvenirs.", translationWord: "die Touristin = tourist (female)", translationSentence: "The female tourists are buying souvenirs." },
  { word: "die Führung", sentence: "Die Führung durch das Museum dauert eine Stunde.", translationWord: "die Führung = guided tour", translationSentence: "The guided tour through the museum lasts an hour." },
  { word: "die Unterkunft", sentence: "Die Unterkunft war einfach, aber gemütlich.", translationWord: "die Unterkunft = accommodation", translationSentence: "The accommodation was simple but cozy." },
  { word: "die Erfahrung", sentence: "Die Reise war eine tolle Erfahrung.", translationWord: "die Erfahrung = experience", translationSentence: "The trip was a great experience." }
);
cards.push(
  { word: "die Gesundheit", sentence: "Gesundheit ist wichtiger als Geld.", translationWord: "die Gesundheit = health", translationSentence: "Health is more important than money." },
  { word: "die Krankheit", sentence: "Die Krankheit dauerte fast zwei Wochen.", translationWord: "die Krankheit = illness", translationSentence: "The illness lasted almost two weeks." },
  { word: "der Patient", sentence: "Der Patient wartet im Wartezimmer.", translationWord: "der Patient = patient (male)", translationSentence: "The patient is waiting in the waiting room." },
  { word: "die Patientin", sentence: "Die Patientin spricht mit der Ärztin.", translationWord: "die Patientin = patient (female)", translationSentence: "The female patient is talking to the doctor." },
  { word: "der Arzt", sentence: "Der Arzt untersucht den Patienten gründlich.", translationWord: "der Arzt = doctor (male)", translationSentence: "The doctor examines the patient thoroughly." },
  { word: "die Ärztin", sentence: "Die Ärztin gibt dem Kind ein Rezept.", translationWord: "die Ärztin = doctor (female)", translationSentence: "The doctor gives the child a prescription." },
  { word: "das Krankenhaus", sentence: "Er musste ins Krankenhaus gebracht werden.", translationWord: "das Krankenhaus = hospital", translationSentence: "He had to be taken to the hospital." },
  { word: "die Apothekerin", sentence: "Die Apothekerin erklärt, wie man das Medikament nimmt.", translationWord: "die Apothekerin = pharmacist (female)", translationSentence: "The pharmacist explains how to take the medicine." },
  { word: "das Medikament", sentence: "Dieses Medikament hilft gegen Kopfschmerzen.", translationWord: "das Medikament = medicine", translationSentence: "This medicine helps against headaches." },
  { word: "die Tablette", sentence: "Nehmen Sie diese Tabletten dreimal täglich.", translationWord: "die Tablette = pill", translationSentence: "Take these pills three times a day." },

  { word: "der Schmerz", sentence: "Er hat starke Schmerzen im Rücken.", translationWord: "der Schmerz = pain", translationSentence: "He has severe pain in his back." },
  { word: "die Verletzung", sentence: "Die Verletzung war nicht lebensgefährlich.", translationWord: "die Verletzung = injury", translationSentence: "The injury was not life-threatening." },
  { word: "das Blut", sentence: "Der Arzt nahm ihm eine Blutprobe ab.", translationWord: "das Blut = blood", translationSentence: "The doctor took a blood sample from him." },
  { word: "das Fieber", sentence: "Das Kind hat hohes Fieber.", translationWord: "das Fieber = fever", translationSentence: "The child has a high fever." },
  { word: "der Husten", sentence: "Der Husten ist nachts besonders stark.", translationWord: "der Husten = cough", translationSentence: "The cough is especially strong at night." },
  { word: "die Grippe", sentence: "Viele Menschen haben im Winter die Grippe.", translationWord: "die Grippe = flu", translationSentence: "Many people catch the flu in winter." },
  { word: "die Ernährung", sentence: "Gesunde Ernährung ist sehr wichtig.", translationWord: "die Ernährung = nutrition/diet", translationSentence: "Healthy nutrition is very important." },
  { word: "das Gewicht", sentence: "Er hat in letzter Zeit viel Gewicht verloren.", translationWord: "das Gewicht = weight", translationSentence: "He has lost a lot of weight recently." },
  { word: "die Diät", sentence: "Sie macht eine Diät, um abzunehmen.", translationWord: "die Diät = diet", translationSentence: "She is on a diet to lose weight." },
  { word: "der Sport", sentence: "Regelmäßiger Sport hält fit.", translationWord: "der Sport = sport", translationSentence: "Regular exercise keeps you fit." },

  { word: "die Bewegung", sentence: "Mehr Bewegung ist gut für die Gesundheit.", translationWord: "die Bewegung = exercise/movement", translationSentence: "More exercise is good for your health." },
  { word: "das Training", sentence: "Das Training beginnt um 18 Uhr.", translationWord: "das Training = training/practice", translationSentence: "The training starts at 6 p.m." },
  { word: "der Wettbewerb", sentence: "Der Wettbewerb findet einmal im Jahr statt.", translationWord: "der Wettbewerb = competition", translationSentence: "The competition takes place once a year." },
  { word: "der Sieg", sentence: "Der Sieg war sehr wichtig für die Mannschaft.", translationWord: "der Sieg = victory", translationSentence: "The victory was very important for the team." },
  { word: "die Niederlage", sentence: "Die Niederlage war für alle eine Enttäuschung.", translationWord: "die Niederlage = defeat", translationSentence: "The defeat was a disappointment for everyone." },
  { word: "der Gewinner", sentence: "Der Gewinner des Spiels bekommt einen Preis.", translationWord: "der Gewinner = winner (male)", translationSentence: "The winner of the game gets a prize." },
  { word: "die Gewinnerin", sentence: "Die Gewinnerin freut sich über ihre Medaille.", translationWord: "die Gewinnerin = winner (female)", translationSentence: "The female winner is happy about her medal." },
  { word: "das Spiel", sentence: "Die Kinder spielen ein neues Spiel.", translationWord: "das Spiel = game", translationSentence: "The children are playing a new game." },
  { word: "der Spieler", sentence: "Der Spieler schießt ein Tor.", translationWord: "der Spieler = player (male)", translationSentence: "The player scores a goal." },
  { word: "die Spielerin", sentence: "Die Spielerin trainiert jeden Tag.", translationWord: "die Spielerin = player (female)", translationSentence: "The female player trains every day." },

  { word: "der Ball", sentence: "Der Ball rollt unter den Tisch.", translationWord: "der Ball = ball", translationSentence: "The ball rolls under the table." },
  { word: "die Mannschaft", sentence: "Die Mannschaft hat hart trainiert.", translationWord: "die Mannschaft = team", translationSentence: "The team trained hard." },
  { word: "das Tor", sentence: "Der Stürmer schießt das entscheidende Tor.", translationWord: "das Tor = goal", translationSentence: "The striker scores the decisive goal." },
  { word: "das Stadion", sentence: "Das Stadion ist fast ausverkauft.", translationWord: "das Stadion = stadium", translationSentence: "The stadium is almost sold out." },
  { word: "die Kultur", sentence: "Die Kultur eines Landes ist sehr vielfältig.", translationWord: "die Kultur = culture", translationSentence: "The culture of a country is very diverse." },
  { word: "die Geschichte", sentence: "Die Geschichte Deutschlands ist sehr komplex.", translationWord: "die Geschichte = history/story", translationSentence: "The history of Germany is very complex." },
  { word: "die Kunst", sentence: "Die Kunstgalerie zeigt moderne Werke.", translationWord: "die Kunst = art", translationSentence: "The art gallery exhibits modern works." },
  { word: "die Literatur", sentence: "Deutsche Literatur ist weltweit bekannt.", translationWord: "die Literatur = literature", translationSentence: "German literature is known worldwide." },
  { word: "das Theater", sentence: "Wir gehen heute Abend ins Theater.", translationWord: "das Theater = theater", translationSentence: "We are going to the theater tonight." },
  { word: "das Kino", sentence: "Das Kino zeigt einen neuen Film.", translationWord: "das Kino = cinema", translationSentence: "The cinema is showing a new movie." },

  { word: "der Film", sentence: "Der Film war spannend und unterhaltsam.", translationWord: "der Film = film/movie", translationSentence: "The film was exciting and entertaining." },
  { word: "die Musik", sentence: "Musik spielt in meinem Leben eine große Rolle.", translationWord: "die Musik = music", translationSentence: "Music plays a big role in my life." },
  { word: "das Lied", sentence: "Das Lied ist sehr bekannt in Deutschland.", translationWord: "das Lied = song", translationSentence: "The song is very well-known in Germany." },
  { word: "der Sänger", sentence: "Der Sänger hat eine schöne Stimme.", translationWord: "der Sänger = singer (male)", translationSentence: "The singer has a beautiful voice." },
  { word: "die Sängerin", sentence: "Die Sängerin singt sehr gefühlvoll.", translationWord: "die Sängerin = singer (female)", translationSentence: "The female singer sings very emotionally." },
  { word: "das Konzert", sentence: "Das Konzert war ausverkauft.", translationWord: "das Konzert = concert", translationSentence: "The concert was sold out." },
  { word: "das Instrument", sentence: "Er spielt seit Jahren ein Instrument.", translationWord: "das Instrument = instrument", translationSentence: "He has been playing an instrument for years." },
  { word: "die Bühne", sentence: "Die Schauspieler standen auf der Bühne.", translationWord: "die Bühne = stage", translationSentence: "The actors stood on the stage." },
  { word: "die Ausstellung", sentence: "Die Ausstellung im Museum ist sehr interessant.", translationWord: "die Ausstellung = exhibition", translationSentence: "The exhibition in the museum is very interesting." },
  { word: "die Veranstaltung", sentence: "Die Veranstaltung beginnt um 20 Uhr.", translationWord: "die Veranstaltung = event", translationSentence: "The event starts at 8 p.m." }
);
